# Generated by Django 5.0 on 2024-01-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='action', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('credential', models.URLField()),
            ],
        ),
    ]
