# Generated by Django 5.0 on 2024-01-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_pages', '0002_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
